/* Communities dummy - FloraVerse */
const COMMUNITIES = [
  {id:"c01", nama:"Pecinta Cabai", slug:"pecinta-cabai", kategori:"Tanaman", members:1240, posts:342, color:"#FF718D", emoji:"🌶️", desc:"Berbagi tips menanam cabai dari semai hingga panen. Cocok untuk pemula dan kolektor pedas.", tags:["#cabai","#sayuran","#rumahan"], cover:"🌶️"},
  {id:"c02", nama:"Tomat Lovers Indonesia", slug:"tomat-lovers", kategori:"Tanaman", members:980, posts:210, color:"#FF9B70", emoji:"🍅", desc:"Komunitas penggemar tomat cherry & beef. Diskusi hama, ajir, dan panen.", tags:["#tomat","#buah","#pot"], cover:"🍅"},
  {id:"c03", nama:"Hidroponik Indonesia", slug:"hidroponik", kategori:"Metode", members:2100, posts:567, color:"#6FA8FF", emoji:"💧", desc:"Urban farming tanpa tanah. AB Mix, NFT, wick system - semua dibahas.", tags:["#hidroponik","#urban","#ABMix"], cover:"💧", coverImg:"https://gokomodo.com/_next/image?url=https%3A%2F%2Fgkmdblog.s3.ap-southeast-1.amazonaws.com%2Fwp-content%2Fuploads%2F2024%2F01%2F16162052%2FBlog-Sayuran-Hidroponik.jpg&w=3840&q=75"},
  {id:"c04", nama:"Urban Gardening Jakarta", slug:"urban-gardening", kategori:"Metode", members:1850, posts:423, color:"#FFD45C", emoji:"🏙️", desc:"Berkebun di balkon, rooftop, dan gang sempit. Kota tetap hijau.", tags:["#urban","#balkon","#kota"], cover:"🏙️", coverImg:"https://lh7-rt.googleusercontent.com/docsz/AD_4nXdIWKouos67dd5O7WjidcdaiSJgbNrD8C3FXEeV4LPahILQDtNWkE4KLgoIS4FjMD6Y9IVxplaMEpoOsVL2qtqVCrBzjlncSc2EhmeUuOi2GT3wuWCBuRyLuPszlI22jwXKgbP95A3mwAHrMy6aXtY2btI?key=7BbeHM1jaxuqjE5cZf29hw"},
  {id:"c05", nama:"Cactus & Succulent ID", slug:"cactus-succulent", kategori:"Hobi", members:3200, posts:812, color:"#8BCB8A", emoji:"🌵", desc:"Kolektor kaktus dan sukulen. Show off roset, tips propagasi.", tags:["#kaktus","#sukulen","#hias"], cover:"🌵", coverImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxnT0Src5pzuXykekoFy0uAfQWBfolnlbOIYfjpOLsQ3L8rrDPVIIK-3pJ&s=10"},
  {id:"c06", nama:"Bonsai Nusantara", slug:"bonsai", kategori:"Hobi", members:870, posts:198, color:"#8BCB8A", emoji:"🌳", desc:"Seni bonsai - dari bakalan hingga kontes. Sabar, presisi, indah.", tags:["#bonsai","#seni","#pohon"], cover:"🌳", coverImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNo3NtEgYOu0_eINh-rcZlBWPrC3Sx0lV9lBEQUipByw&s=10"},
  {id:"c07", nama:"Kebun Buah Rumahan", slug:"kebun-buah", kategori:"Tanaman", members:640, posts:156, color:"#FFD45C", emoji:"🍓", desc:"Stroberi, mangga tabulampot, jeruk kalamansi - buah di rumah.", tags:["#buah","#tabulampot","#panen"], cover:"🍓"},
  {id:"c08", nama:"Organic Gardening", slug:"organic", kategori:"Metode", members:1120, posts:298, color:"#8BCB8A", emoji:"♻️", desc:"Berkebun organik, kompos, tanpa pestisida sintetis.", tags:["#organik","#kompos","#sehat"], cover:"♻️", coverImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3HNkexjdFPuP6tTSBfmszLdNh8yR9_rE2P4bJ5551mCViQddcxfnbKsg&s=10"},
  {id:"c09", nama:"Home Gardening Pemula", slug:"home-gardening", kategori:"Hobi", members:2650, posts:734, color:"#6FA8FF", emoji:"🏡", desc:"Ruang aman untuk pemula bertanya tanpa takut di-judge.", tags:["#pemula","#belajar","#sharing"], cover:"🏡", coverImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSScA82wbWZ6D6K_0I-4ZTX41UyLUIP6BX3VozuvXtS1CMsA1rYbbhnaa_k&s=10"},
  {id:"c10", nama:"Flower Garden", slug:"flower-garden", kategori:"Hobi", members:920, posts:210, color:"#FF718D", emoji:"🌸", desc:"Mawar, matahari, anggrek - taman bunga untuk healing.", tags:["#bunga","#mawar","#anggrek"], cover:"🌸"},
  {id:"c11", nama:"Composting Crew", slug:"composting", kategori:"Metode", members:540, posts:112, color:"#8BCB8A", emoji:"🍂", desc:"Olah sampah dapur jadi emas hitam. Kompos, kascing, eco-enzyme.", tags:["#kompos","#zerowaste","#lingkungan"], cover:"🍂", coverImg:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROIQHk8FU9NZO668ab81SmNS_xT6rYhbiVZA-Xsz9j6ufVdBXdl_kvIwA&s=10"},
  {id:"c12", nama:"Herb & Rempah", slug:"herb-rempah", kategori:"Tanaman", members:760, posts:178, color:"#8BCB8A", emoji:"🌿", desc:"Basil, mint, kemangi, lavender - herbal untuk dapur & relaksasi.", tags:["#herbal","#rempah","#dapur"], cover:"🌿"}
];

const COMMUNITY_PLANTS = {c01:"cabai-rawit", c02:"tomat", c05:"kaktus", c07:"stroberi", c10:"mawar", c12:"basil"};
COMMUNITIES.forEach(community => { if(COMMUNITY_PLANTS[community.id]) community.plantId = COMMUNITY_PLANTS[community.id]; });

/* Dummy posts - digunakan di community.html */
const POSTS = [
  {id:"post-cabai-rawit", community:"c01", user:"Izra", avatar:"IZ", time:"2 jam lalu", content:"Cabai rawit ku hari ke-28 udah mulai berbunga! Siram tiap pagi + pupuk organik 2 minggu sekali. Ada tips biar buah lebat?", likes:42, comments:12, plantId:"cabai-rawit", liked:false, saved:false, tags:["#cabai","#berbunga"]},
  {id:"post-selada", community:"c03", user:"Fairuz", avatar:"FA", time:"5 jam lalu", content:"Panen selada romaine hidroponik 35 hari! AB Mix 800ppm, pH 6.0. Rasanya renyah banget. Siapa mau resep nutrisi?", likes:89, comments:24, plantId:"selada", liked:true, saved:false, tags:["#hidroponik","#panen"]},
  {id:"post-sukulen", community:"c05", user:"Tafayad", avatar:"TA", time:"1 hari lalu", content:"Sukulen echeveria ku propagation dari daun, 3 minggu udah berakar. Jangan siram daun ya!", likes:67, comments:9, plantId:"sukulen", liked:false, saved:true, tags:["#sukulen","#propagasi"]},
  {id:"post-balkon", community:"c09", user:"Izra", avatar:"IZ", time:"1 hari lalu", content:"Baru mulai berkebun di balkon 2x1m. Rekomendasi tanaman yang tahan panas dan jarang siram?", likes:31, comments:18, image:"🏡", liked:false, saved:false, tags:["#pemula","#balkon"]},
  {id:"post-tomat", community:"c02", user:"Fairuz", avatar:"FA", time:"2 hari lalu", content:"Tomat cherry ku kena blossom end rot 😭 Ternyata kurang kalsium + siram tidak konsisten. Sudah tambah kalsium boron, semoga membaik.", likes:54, comments:15, plantId:"tomat", liked:false, saved:false, tags:["#tomat","#hama"]},
  {id:"post-kompos", community:"c08", user:"Tafayad", avatar:"TA", time:"3 hari lalu", content:"Kompos dari sampah dapur 30 hari jadi! Bau tanah, hitam, remah. Gratis dan ramah lingkungan ♻️", likes:76, comments:11, image:"♻️", liked:true, saved:false, tags:["#kompos","#organik"]},
  {id:"post-mawar", community:"c10", user:"Izra", avatar:"IZ", time:"3 hari lalu", content:"Mawar floribunda ku mekar kedua kali. Pangkas miring 45° ternyata ngaruh banget!", likes:48, comments:7, plantId:"mawar", liked:false, saved:false, tags:["#mawar","#bunga"]},
  {id:"post-stroberi", community:"c07", user:"Fairuz", avatar:"FA", time:"4 hari lalu", content:"Stroberi albion pot gantung buah pertama! Harus sabar 90 hari tapi worth it 🍓", likes:93, comments:22, plantId:"stroberi", liked:false, saved:true, tags:["#stroberi","#potgantung"]},
  {id:"post-kangkung", community:"c04", user:"Tafayad", avatar:"TA", time:"4 hari lalu", content:"Urban gardening itu terapi. Pagi siram, sore panen kangkung 25 hari. Kota tetap hijau!", likes:61, comments:13, plantId:"kangkung", liked:false, saved:false, tags:["#urban","#kangkung"]},
  {id:"post-mint", community:"c12", user:"Izra", avatar:"IZ", time:"5 hari lalu", content:"Mint ku invasi pot lain 😅 Pelajaran: jangan tanam mint campur! Pisahkan pot.", likes:39, comments:10, plantId:"mint", liked:false, saved:false, tags:["#mint","#herbal"]},
];

/* Dummy comments per post */
const DUMMY_COMMENTS={
"post-cabai-rawit":[
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Keren Izra! Coba kasih pupuk K tinggi biar buah lebat 🌶️"},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Gue juga nanam cabai di polybag, 70 hari udah panen pertama."},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Pakai media tanam apa? Aku mau coba juga."},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"Cabai rawit emang paling intense rasa pedasnya!"},
{user:"Dimas",avatar:"DI",color:"#FFD45C",text:"Aku juga lagi nanam, tapi masih hari ke-14 nih."},
{user:"Raka",avatar:"RA",color:"#8BCB8A",text:"Tunggu update selanjutnya ya, penasaran hasilnya!"},
],
"post-selada":[
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"Wah seladanya bagus! AB Mix nya beli dimana?"},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"35 hari udah panen, cepet banget. Gue harus coba nih."},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Resep nutrisinya dong! Mau share ke komunitas hidroponik juga."},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"pH 6.0 itu range ideal ya? Atau bisa lebih tinggi?"},
{user:"Raka",avatar:"RA",color:"#8BCB8A",text:"Aku pakai wick system, hasilnya beda jauh sama NFT."},
{user:"Dimas",avatar:"DI",color:"#FFD45C",text:"Mantap! Aku lagi nyoba romaine juga nih."},
],
"post-sukulen":[
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"Bagus banget rosetnya! Echeveria jenis apa nih?"},
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Tipsnya jangan siram daun emang bener, pernah ku coba malah busuk."},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Propagasi dari daun emang paling reliable buat sukulen."},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"3 minggu udah berakar, cepet banget! Aku pernah sampe sebulan."},
],
"post-balkon":[
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Coba tanam mint atau kemangi, tahan panas dan ga ribet!"},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Kangkung juga bisa, 25 hari udah panen. Cocok buat balkon."},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"Selada cherry juga tahan panas kalau dikasih naungan ringan."},
{user:"Raka",avatar:"RA",color:"#8BCB8A",text:"Aku saranin pakai pot gantung, hemat tempat di balkon kecil."},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Tomat cherry juga oke di balkon, asal sinar matahari cukup."},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Pakai self-watering pot biar ga perlu siram tiap hari."},
{user:"Dimas",avatar:"DI",color:"#FFD45C",text:"Stroberi juga bisa di balkon loh, asal potnya cukup dalam."},
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"Makasih semua rekomendasinya! Mulai dari kangkung aja deh."},
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Update ya kalau udah mulai nanam! Penasaran hasilnya."},
],
"post-tomat":[
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"Blossom end rot emang frustrating. Semoga cepet membaik!"},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Kalsium boron nya beli dimana? Aku juga pernah kena ini."},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"Siram konsisten itu kunci memang. Aku pakai timer sekarang."},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Semoga tomatnya recovery ya Fairuz!"},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Tambahin mulsa juga bisa bantu jaga kelembaban tanah."},
],
"post-kompos":[
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"30 hari jadi! Cepet banget. Pakai EM4 ga?"},
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Ga bau ya? Aku takut bau kalau kompos di rumah."},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Share tips dong, aku mau mulai kompos juga."},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Eco-enzyme nya juga keren! Aku udah coba bikin."},
{user:"Raka",avatar:"RA",color:"#8BCB8A",text:"Sampah dapur jadi emas hitam, literally. Mantap Tafayad!"},
{user:"Dimas",avatar:"DI",color:"#FFD45C",text:"Aku mau coba juga, tapi takut lambat prosesnya."},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"Kompos rumah lebih aman dan hemat dari beli."},
],
"post-mawar":[
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Pangkas miring 45° itu penting biar air ga ngendap di bekas potongan."},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Floribunda memang rajin mekar. Aku juga punya satu."},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"Mekar kedua kali artinya sehat banget tuh mawarnya!"},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Berapa lama jarak pangkas sampe mekar lagi?"},
{user:"Dimas",avatar:"DI",color:"#FFD45C",text:"Kasih pupuk khusus mawar ga? Aku lagi cari rekomendasi."},
],
"post-stroberi":[
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"90 hari sabar banget! Albion emang worth it."},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Pot gantung stroberi cantik banget! Share dong foto close-up nya."},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Albion itu day neutral ya? Jadi bisa terus berbuah?"},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Aku udah 2x gagal nanam stroberi. Tips biar berhasil dong."},
{user:"Raka",avatar:"RA",color:"#8BCB8A",text:"Media tanam apa yang dipakai? Aku dengar pakai cocopeat bagus."},
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Buah pertama itu special moment banget 🍓"},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"Pot gantung hemat tempat, strategis buat balkon."},
{user:"Dimas",avatar:"DI",color:"#FFD45C",text:"Aku juga mau coba albion, tapi takut ga sabar 90 hari 😅"},
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"Fairuz ini inspirasi banget! Aku jadi mau coba stroberi."},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Kalau udah panen, share resep juga ya!"},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Stroberi + whipped cream = heaven 🍓🍦"},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Aku fokus kaktus dulu deh, masih trauma gagal stroberi 😂"},
{user:"Raka",avatar:"RA",color:"#8BCB8A",text:"Ga ada yang gagal, yang ada trial and error! 💪"},
],
"post-kangkung":[
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"25 hari panen! Cepet banget. Cocok buat pemula."},
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Urban gardening memang terapi. Aktivitas outdoor di kota."},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Kangkung organizer vertical juga bisa hemat tempat."},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Kangkung goreng camilan favorit! Panen sendiri lebih nikmat."},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Aku nanam kangkung di aquaponics, hasilnya joss!"},
{user:"Dimas",avatar:"DI",color:"#FFD45C",text:"25 hari itu tergantung varietas ya? Atau semua sama?"},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"Kangkung air memang super cepat tumbuhnya."},
{user:"Raka",avatar:"RA",color:"#8BCB8A",text:"Taman kota memang healing. Aku juga di Jakarta nanam kangkung."},
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Kota tetap bisa hijau! 💚"},
],
"post-mint":[
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Haha mint emang invasion species di dunia tanaman! 🌿"},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Tip: tanam mint di pot terpisah, taruh di tengah kebun biar wangi."},
{user:"Sari",avatar:"SA",color:"#FF718D",text:"Mint tea dari hasil panen sendiri, next level!"},
{user:"Alif",avatar:"AL",color:"#FF9B70",text:"Aku juga pernah, mint ku nyampur sama selada. Ga kelar-kelar 😂"},
{user:"Nadia",avatar:"NA",color:"#FF718D",text:"Mojito homemade dari mint sendiri 🍹"},
{user:"Raka",avatar:"RA",color:"#8BCB8A",text:"Mint chocolate chip ice cream dari mint kebun? 🍦"},
{user:"Dimas",avatar:"DI",color:"#FFD45C",text:"Jadi pengen nanam mint juga deh. Susah ga sih?"},
{user:"Izra",avatar:"IZ",color:"#6FA8FF",text:"Ga susah, malah terlalu gampang sampe invasion 😅"},
{user:"Fairuz",avatar:"FA",color:"#FFD45C",text:"Mint = low maintenance high reward plant 🌿✨"},
{user:"Tafayad",avatar:"TA",color:"#8BCB8A",text:"Paling enak mojito mint segar dari kebun sendiri 🍹"},
],
};
