/* FloraShop dummy products - FloraVerse */
const PRODUCTS = [
  {id:"p01", nama:"Benih Cabai Rawit 50 Biji", kategori:"Benih", harga:15000, rating:4.8, ulas:342, badge:"Best Seller", emoji:"🌶️", img:"assets/photos/products/p01.jpg", related:"cabai-rawit", stok:120},
  {id:"p02", nama:"Benih Tomat Cherry 30 Biji", kategori:"Benih", harga:18000, rating:4.7, ulas:210, badge:"Popular", emoji:"🍅", img:"assets/photos/products/p02.jpg", related:"tomat", stok:80},
  {id:"p03", nama:"Benih Selada Romaine", kategori:"Benih", harga:12000, rating:4.6, ulas:180, badge:"Beginner Pick", emoji:"🥬", img:"assets/photos/products/p03.jpg", related:"selada", stok:95},
  {id:"p04", nama:"Pot Keramik 20cm - Putih", kategori:"Pot", harga:45000, rating:4.9, ulas:412, badge:"Recommended", emoji:"🪴", img:"assets/photos/products/p04.jpg", related:"cabai-rawit", stok:60},
  {id:"p05", nama:"Polybag 25x25 10pcs", kategori:"Pot", harga:15000, rating:4.5, ulas:98, badge:"", emoji:"🪴", img:"assets/photos/products/p05.jpg", related:"bayam", stok:200},
  {id:"p06", nama:"Media Tanam Premium 5kg", kategori:"Media Tanam", harga:32000, rating:4.8, ulas:523, badge:"Best Seller", emoji:"🌿", img:"assets/photos/products/p06.jpg", related:"tomat", stok:70},
  {id:"p07", nama:"Cocopeat Block 650gr", kategori:"Media Tanam", harga:18000, rating:4.6, ulas:156, badge:"", emoji:"🥥", img:"assets/photos/products/p07.jpg", related:"selada", stok:110},
  {id:"p08", nama:"Sekam Bakar 3kg", kategori:"Media Tanam", harga:12000, rating:4.7, ulas:201, badge:"", emoji:"🌾", img:"assets/photos/products/p08.jpg", related:"wortel", stok:90},
  {id:"p09", nama:"Kompos Organik 5kg", kategori:"Pupuk", harga:25000, rating:4.8, ulas:334, badge:"Popular", emoji:"♻️", img:"assets/photos/products/p09.jpg", related:"bayam", stok:85},
  {id:"p10", nama:"Pupuk Organik Cair 500ml", kategori:"Pupuk", harga:20000, rating:4.7, ulas:289, badge:"Recommended", emoji:"🧪", img:"assets/photos/products/p10.jpg", related:"cabai-rawit", stok:75},
  {id:"p11", nama:"NPK 16-16-16 1kg", kategori:"Pupuk", harga:28000, rating:4.6, ulas:167, badge:"", emoji:"🧪", img:"assets/photos/products/p11.jpg", related:"tomat", stok:65},
  {id:"p12", nama:"Sprayer 2L - Biru", kategori:"Tools", harga:35000, rating:4.7, ulas:221, badge:"New", emoji:"💦", img:"assets/photos/products/p12.jpg", related:"mawar", stok:40},
  {id:"p13", nama:"Sekop Mini Kayu", kategori:"Tools", harga:22000, rating:4.5, ulas:112, badge:"", emoji:"🪓", img:"assets/photos/products/p13.jpg", related:"wortel", stok:55},
  {id:"p14", nama:"Gunting Tanaman Tajam", kategori:"Tools", harga:30000, rating:4.8, ulas:298, badge:"Popular", emoji:"✂️", img:"assets/photos/products/p14.jpg", related:"basil", stok:45},
  {id:"p15", nama:"Starter Kit Hidroponik 6 Lubang", kategori:"Hydroponics", harga:125000, rating:4.9, ulas:401, badge:"Best Seller", emoji:"💧", img:"assets/photos/products/p15.jpg", related:"selada", stok:30},
  {id:"p16", nama:"Netpot 5cm 20pcs", kategori:"Hydroponics", harga:15000, rating:4.6, ulas:134, badge:"", emoji:"🥤", img:"assets/photos/products/p16.jpg", related:"kangkung", stok:120},
  {id:"p17", nama:"Nutrisi AB Mix 500ml", kategori:"Hydroponics", harga:35000, rating:4.8, ulas:267, badge:"Recommended", emoji:"🧴", img:"assets/photos/products/p17.jpg", related:"selada", stok:80},
  {id:"p18", nama:"Benih Kangkung 100 Biji", kategori:"Benih", harga:10000, rating:4.6, ulas:187, badge:"Beginner Pick", emoji:"🥬", img:"assets/photos/products/p18.jpg", related:"kangkung", stok:150},
  {id:"p19", nama:"Benih Basil 50 Biji", kategori:"Benih", harga:14000, rating:4.8, ulas:203, badge:"Popular", emoji:"🌿", img:"assets/photos/products/p19.jpg", related:"basil", stok:100},
  {id:"p20", nama:"Pot Gantung 18cm", kategori:"Pot", harga:28000, rating:4.7, ulas:176, badge:"New", emoji:"🪴", img:"assets/photos/products/p20.jpg", related:"stroberi", stok:50},
  {id:"p21", nama:"Pupuk Kalsium + Boron", kategori:"Pupuk", harga:32000, rating:4.5, ulas:98, badge:"", emoji:"🧪", img:"assets/photos/products/p21.jpg", related:"tomat", stok:60},
  {id:"p22", nama:"Tray Semai 72 Lubang", kategori:"Tools", harga:18000, rating:4.6, ulas:143, badge:"", emoji:"🧊", img:"assets/photos/products/p22.jpg", related:"cabai-rawit", stok:70},
  {id:"p23", nama:"Benih Bunga Matahari 10 Biji", kategori:"Benih", harga:16000, rating:4.8, ulas:165, badge:"Recommended", emoji:"🌻", img:"assets/photos/products/p23.jpg", related:"matahari", stok:85},
  {id:"p24", nama:"Media Sukulen 2kg", kategori:"Media Tanam", harga:22000, rating:4.7, ulas:132, badge:"", emoji:"🌵", img:"assets/photos/products/p24.jpg", related:"sukulen", stok:60},
  {id:"p25", nama:"Chili Starter Kit (Bundling)", kategori:"Bundling", harga:65000, rating:4.9, ulas:512, badge:"Best Seller", emoji:"🎁", img:"assets/photos/products/p25.jpg", related:"cabai-rawit", stok:40},
  {id:"p26", nama:"Tomato Starter Kit", kategori:"Bundling", harga:72000, rating:4.8, ulas:298, badge:"Popular", emoji:"🎁", img:"assets/photos/products/p26.jpg", related:"tomat", stok:35},
  {id:"p27", nama:"Herb Starter Kit (Basil+Mint)", kategori:"Bundling", harga:58000, rating:4.7, ulas:210, badge:"Beginner Pick", emoji:"🎁", img:"assets/photos/products/p27.jpg", related:"basil", stok:45},
  {id:"p28", nama:"Hidroponik Pemula Kit", kategori:"Bundling", harga:145000, rating:4.8, ulas:187, badge:"New", emoji:"🎁", img:"assets/photos/products/p28.jpg", related:"selada", stok:25},
  {id:"p29", nama:"Bibit Cabai Rawit Siap Tanam 3 Batang", kategori:"Bibit", harga:12000, rating:4.7, ulas:156, badge:"New", emoji:"🌱", img:"assets/photos/products/p29.jpg", related:"cabai-rawit", stok:70},
  {id:"p30", nama:"Neem Oil 100ml - Obat Hama Organik", kategori:"Plant care", harga:25000, rating:4.8, ulas:201, badge:"Recommended", emoji:"🧴", img:"assets/photos/products/p30.jpg", related:"tomat", stok:60},
  {id:"p31", nama:"Bibit Tomat Cherry Siap Tanam", kategori:"Bibit", harga:15000, rating:4.7, ulas:132, badge:"Beginner Pick", emoji:"🌱", img:"assets/photos/products/p31.jpg", related:"tomat", stok:55},
  {id:"p32", nama:"Pupuk Daun Plant Care Spray", kategori:"Plant care", harga:18000, rating:4.6, ulas:98, badge:"Popular", emoji:"💦", img:"assets/photos/products/p32.jpg", related:"mawar", stok:80}
];

