/* FloraShop dummy products - FloraVerse */
const PRODUCTS = [
  {id:"benih-cabai-rawit-50-biji", nama:"Benih Cabai Rawit 50 Biji", kategori:"Benih", harga:15000, rating:4.8, ulas:342, badge:"Best Seller", emoji:"🌶️", related:"cabai-rawit", stok:120},
  {id:"benih-tomat-cherry-30-biji", nama:"Benih Tomat Cherry 30 Biji", kategori:"Benih", harga:18000, rating:4.7, ulas:210, badge:"Popular", emoji:"🍅", related:"tomat", stok:80},
  {id:"benih-selada-romaine", nama:"Benih Selada Romaine", kategori:"Benih", harga:12000, rating:4.6, ulas:180, badge:"Beginner Pick", emoji:"🥬", related:"selada", stok:95},
  {id:"pot-keramik-20cm-putih", nama:"Pot Keramik 20cm - Putih", kategori:"Pot", harga:45000, rating:4.9, ulas:412, badge:"Recommended", emoji:"🪴", related:"cabai-rawit", stok:60},
  {id:"polybag-25x25-10pcs", nama:"Polybag 25x25 10pcs", kategori:"Pot", harga:15000, rating:4.5, ulas:98, badge:"", emoji:"🪴", related:"bayam", stok:200},
  {id:"media-tanam-premium-5kg", nama:"Media Tanam Premium 5kg", kategori:"Media Tanam", harga:32000, rating:4.8, ulas:523, badge:"Best Seller", emoji:"🌿", related:"tomat", stok:70},
  {id:"cocopeat-block-650gr", nama:"Cocopeat Block 650gr", kategori:"Media Tanam", harga:18000, rating:4.6, ulas:156, badge:"", emoji:"🥥", related:"selada", stok:110},
  {id:"sekam-bakar-3kg", nama:"Sekam Bakar 3kg", kategori:"Media Tanam", harga:12000, rating:4.7, ulas:201, badge:"", emoji:"🌾", related:"wortel", stok:90},
  {id:"kompos-organik-5kg", nama:"Kompos Organik 5kg", kategori:"Pupuk", harga:25000, rating:4.8, ulas:334, badge:"Popular", emoji:"♻️", related:"bayam", stok:85},
  {id:"pupuk-organik-cair-500ml", nama:"Pupuk Organik Cair 500ml", kategori:"Pupuk", harga:20000, rating:4.7, ulas:289, badge:"Recommended", emoji:"🧪", related:"cabai-rawit", stok:75},
  {id:"npk-16-16-16-1kg", nama:"NPK 16-16-16 1kg", kategori:"Pupuk", harga:28000, rating:4.6, ulas:167, badge:"", emoji:"🧪", related:"tomat", stok:65},
  {id:"sprayer-2l-biru", nama:"Sprayer 2L - Biru", kategori:"Tools", harga:35000, rating:4.7, ulas:221, badge:"New", emoji:"💦", related:"mawar", stok:40},
  {id:"sekop-mini-kayu", nama:"Sekop Mini Kayu", kategori:"Tools", harga:22000, rating:4.5, ulas:112, badge:"", emoji:"🪓", related:"wortel", stok:55},
  {id:"gunting-tanaman-tajam", nama:"Gunting Tanaman Tajam", kategori:"Tools", harga:30000, rating:4.8, ulas:298, badge:"Popular", emoji:"✂️", related:"basil", stok:45},
  {id:"starter-kit-hidroponik-6-lubang", nama:"Starter Kit Hidroponik 6 Lubang", kategori:"Hydroponics", harga:125000, rating:4.9, ulas:401, badge:"Best Seller", emoji:"💧", related:"selada", stok:30},
  {id:"netpot-5cm-20pcs", nama:"Netpot 5cm 20pcs", kategori:"Hydroponics", harga:15000, rating:4.6, ulas:134, badge:"", emoji:"🥤", related:"kangkung", stok:120},
  {id:"nutrisi-ab-mix-500ml", nama:"Nutrisi AB Mix 500ml", kategori:"Hydroponics", harga:35000, rating:4.8, ulas:267, badge:"Recommended", emoji:"🧴", related:"selada", stok:80},
  {id:"benih-kangkung-100-biji", nama:"Benih Kangkung 100 Biji", kategori:"Benih", harga:10000, rating:4.6, ulas:187, badge:"Beginner Pick", emoji:"🥬", related:"kangkung", stok:150},
  {id:"benih-basil-50-biji", nama:"Benih Basil 50 Biji", kategori:"Benih", harga:14000, rating:4.8, ulas:203, badge:"Popular", emoji:"🌿", related:"basil", stok:100},
  {id:"pot-gantung-18cm", nama:"Pot Gantung 18cm", kategori:"Pot", harga:28000, rating:4.7, ulas:176, badge:"New", emoji:"🪴", related:"stroberi", stok:50},
  {id:"pupuk-kalsium-boron", nama:"Pupuk Kalsium + Boron", kategori:"Pupuk", harga:32000, rating:4.5, ulas:98, badge:"", emoji:"🧪", related:"tomat", stok:60},
  {id:"tray-semai-72-lubang", nama:"Tray Semai 72 Lubang", kategori:"Tools", harga:18000, rating:4.6, ulas:143, badge:"", emoji:"🧊", related:"cabai-rawit", stok:70},
  {id:"benih-bunga-matahari-10-biji", nama:"Benih Bunga Matahari 10 Biji", kategori:"Benih", harga:16000, rating:4.8, ulas:165, badge:"Recommended", emoji:"🌻", related:"matahari", stok:85},
  {id:"media-sukulen-2kg", nama:"Media Sukulen 2kg", kategori:"Media Tanam", harga:22000, rating:4.7, ulas:132, badge:"", emoji:"🌵", related:"sukulen", stok:60},
  {id:"chili-starter-kit-bundling", nama:"Chili Starter Kit (Bundling)", kategori:"Bundling", harga:65000, rating:4.9, ulas:512, badge:"Best Seller", emoji:"🎁", related:"cabai-rawit", stok:40},
  {id:"tomato-starter-kit", nama:"Tomato Starter Kit", kategori:"Bundling", harga:72000, rating:4.8, ulas:298, badge:"Popular", emoji:"🎁", related:"tomat", stok:35},
  {id:"herb-starter-kit-basil-mint", nama:"Herb Starter Kit (Basil+Mint)", kategori:"Bundling", harga:58000, rating:4.7, ulas:210, badge:"Beginner Pick", emoji:"🎁", related:"basil", stok:45},
  {id:"hidroponik-pemula-kit", nama:"Hidroponik Pemula Kit", kategori:"Bundling", harga:145000, rating:4.8, ulas:187, badge:"New", emoji:"🎁", related:"selada", stok:25},
  {id:"bibit-cabai-rawit-siap-tanam-3-batang", nama:"Bibit Cabai Rawit Siap Tanam 3 Batang", kategori:"Bibit", harga:12000, rating:4.7, ulas:156, badge:"New", emoji:"🌱", related:"cabai-rawit", stok:70},
  {id:"neem-oil-100ml-obat-hama-organik", nama:"Neem Oil 100ml - Obat Hama Organik", kategori:"Plant care", harga:25000, rating:4.8, ulas:201, badge:"Recommended", emoji:"🧴", related:"tomat", stok:60},
  {id:"bibit-tomat-cherry-siap-tanam", nama:"Bibit Tomat Cherry Siap Tanam", kategori:"Bibit", harga:15000, rating:4.7, ulas:132, badge:"Beginner Pick", emoji:"🌱", related:"tomat", stok:55},
  {id:"pupuk-daun-plant-care-spray", nama:"Pupuk Daun Plant Care Spray", kategori:"Plant care", harga:18000, rating:4.6, ulas:98, badge:"Popular", emoji:"💦", related:"mawar", stok:80}
];
