/* The visualization is generated from comments and parentId — no node or root positions are hard-coded. */
const rootId=String(new URLSearchParams(location.search).get('id')||1);
const root=communityRoots.find(r=>String(r.id)===rootId)||communityRoots[0];
const comments=communityComments.filter(c=>c.rootPostId===root.id).map(c=>c.parentId===root.id?Object.assign({},c,{parentId:'post'}):Object.assign({},c));
const el=id=>document.querySelector(id);
el('#postAvatar').textContent=root.avatar;
el('#postAuthor').textContent=root.author;
el('#postTime').textContent=root.time;
el('#postTitle').textContent=root.title;
el('#postContent').textContent=root.content;
el('#postFooter').textContent=root.reactions+' reactions · '+root.replies+' replies';
el('#threadTitle').textContent=root.tag+' discussion';
const byId=new Map(comments.map(c=>[c.id,c]));
const children=id=>comments.filter(c=>c.parentId===id);
const open=new Set(['post']);let added=new Set(),zoom=1;
const canvas=el('#rootCanvas'),viewport=el('#rootViewport'),layer=el('#commentLayer'),svg=el('#rootLines'),hint=el('#networkHint');
function visibleTree(){const out=[];function walk(parent){children(parent).forEach(child=>{out.push(child);if(open.has(child.id))walk(child.id)})}walk('post');return out}
function depth(id){let d=1,p=byId.get(id);while(p&&p.parentId!=='post'){d++;p=byId.get(p.parentId)}return d}
function layoutDesktop(nodes,available){const visibleIds=new Set(nodes.map(n=>n.id));const childList=id=>children(id).filter(n=>visibleIds.has(n.id));let leaf=0;const x=new Map();function place(id){const kids=childList(id);if(!kids.length){x.set(id,leaf++);return x.get(id)}const positions=kids.map(k=>place(k.id));const value=positions.reduce((a,b)=>a+b,0)/positions.length;x.set(id,value);return value}children('post').filter(n=>visibleIds.has(n.id)).forEach(n=>place(n.id));const cardW=Math.max(132,Math.min(200,Math.floor((available-42)/Math.max(1,leaf)-18)));const gap=leaf>1?(available-cardW-40)/(leaf-1):0,pos=new Map();nodes.forEach(n=>pos.set(n.id,{x:20+x.get(n.id)*gap,y:26+(depth(n.id)-1)*158}));return{pos,width:available,cardW,height:Math.max(270,80+Math.max(...nodes.map(n=>depth(n.id)))*158)}}
function layoutMobile(nodes,available){const pos=new Map();let row=0;function walk(id,d){children(id).filter(n=>nodes.some(v=>v.id===n.id)).forEach(n=>{pos.set(n.id,{x:20+d*14,y:25+row*112});row++;if(open.has(n.id))walk(n.id,d+1)})}walk('post',0);return{pos,width:available,cardW:190,height:Math.max(220,row*112+22)}}
function curve(a,b,seed){const sway=((seed.length*17)%26)-13;const dy=Math.max(48,(b.y-a.y)*.44);return'M '+a.x+' '+a.y+' C '+(a.x+sway)+' '+(a.y+dy)+', '+(b.x-sway)+' '+(b.y-dy)+', '+b.x+' '+b.y}
function path(d,className,parent,child,width,opacity){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('class',className);p.dataset.parent=parent;p.dataset.child=child;p.style.stroke=className.includes('root-hair')?'#b9a665':className.includes('root-stem')?'#b87543':'#d8a663';p.style.strokeWidth=width;p.style.opacity=opacity;svg.append(p);if(added.has(child)){p.style.setProperty('--length',p.getTotalLength())}return p}
function render(){const nodes=visibleTree(),mobile=innerWidth<761,available=Math.max(320,viewport.clientWidth||innerWidth-36),layout=mobile?layoutMobile(nodes,available):layoutDesktop(nodes,available),pos=layout.pos,nodeWidth=id=>mobile?Math.min(190,available-40-(depth(id)-1)*14):layout.cardW;canvas.style.width=layout.width+'px';canvas.style.height=layout.height+'px';svg.setAttribute('viewBox','0 0 '+layout.width+' '+layout.height);svg.setAttribute('width',layout.width);svg.setAttribute('height',layout.height);svg.innerHTML='';layer.innerHTML='';
const rootAnchor={x:available/2,y:0};const nodeHeight=mobile?77:82;const stems=new Map(),origins=new Map(),direct=children('post').filter(k=>pos.has(k.id));direct.forEach((child,index)=>{const spread=(index-(direct.length-1)/2)*Math.min(72,250/direct.length);const start={x:rootAnchor.x+spread,y:0},end={x:start.x+(index%2?5:-5),y:18};origins.set(child.id,end);path('M '+start.x+' '+start.y+' C '+start.x+' 7, '+end.x+' 10, '+end.x+' '+end.y,'dynamic-root root-stem','post',child.id,7.5,.92)});nodes.forEach(node=>{const kids=children(node.id).filter(k=>pos.has(k.id));if(!kids.length)return;const nodeW=nodeWidth(node.id);const source={x:pos.get(node.id).x+nodeW/2,y:pos.get(node.id).y+nodeHeight};const end={x:source.x+((node.id.length%3)-1)*3,y:source.y+20};stems.set(node.id,end);path('M '+source.x+' '+source.y+' C '+source.x+' '+(source.y+9)+', '+end.x+' '+(end.y-8)+', '+end.x+' '+end.y,'dynamic-root root-stem',node.id,node.id,Math.max(3,7-depth(node.id)),.9)});
nodes.forEach(n=>{const parentEnd=n.parentId==='post'?origins.get(n.id):stems.get(n.parentId);if(!parentEnd)return;const nodeW=nodeWidth(n.id);const end={x:pos.get(n.id).x+nodeW/2,y:pos.get(n.id).y};const level=depth(n.id);const main=path(curve(parentEnd,end,n.id),'dynamic-root '+(added.has(n.id)?'is-growing':''),n.parentId,n.id,Math.max(2.2,8-level*1.25),Math.max(.54,1-level*.08));if(added.has(n.id))main.classList.add('is-growing');const hairStart={x:parentEnd.x+(end.x-parentEnd.x)*.58,y:parentEnd.y+(end.y-parentEnd.y)*.58};const hairEnd={x:hairStart.x+((n.id.length*9)%22-11),y:hairStart.y+22};path('M '+hairStart.x+' '+hairStart.y+' C '+(hairStart.x+8)+' '+(hairStart.y+8)+', '+(hairEnd.x-8)+' '+(hairEnd.y-6)+', '+hairEnd.x+' '+hairEnd.y,'dynamic-root root-hair',n.parentId,n.id,Math.max(1,2.2-level*.2),.32)});
nodes.forEach(n=>{const nodeW=nodeWidth(n.id);const card=document.createElement('button');card.className='root-card '+(added.has(n.id)?'is-new':'');card.dataset.id=n.id;card.style.left=pos.get(n.id).x+'px';card.style.top=pos.get(n.id).y+'px';card.style.width=nodeW+'px';card.innerHTML='<span class="node-top"><span class="avatar">'+n.avatar+'</span><span><b>'+n.author+'</b><time>'+n.time+'</time></span></span><strong>'+n.text+'</strong><em>'+n.meta+(children(n.id).length?' · tap to grow':'')+'</em>';card.addEventListener('mouseenter',()=>highlight(n.id));card.addEventListener('mouseleave',clearHighlight);card.addEventListener('focus',()=>highlight(n.id));card.addEventListener('blur',clearHighlight);card.addEventListener('click',()=>toggle(n.id));layer.append(card)});added.clear()}
function highlight(id){const chain=new Set();let current=id;while(current&&current!=='post'){chain.add(current);current=byId.get(current).parentId}document.querySelectorAll('.dynamic-root').forEach(p=>p.classList.toggle('is-highlight',chain.has(p.dataset.child)||chain.has(p.dataset.parent)))}
function clearHighlight(){document.querySelectorAll('.is-highlight').forEach(p=>p.classList.remove('is-highlight'))}
function toggle(id){const kids=children(id);if(!kids.length){hint.textContent='This root has reached a helpful answer.';return}if(open.has(id)){open.delete(id);hint.textContent='This branch is folded. Tap it again to grow the replies.'}else{open.add(id);kids.forEach(k=>added.add(k.id));hint.textContent='A new set of roots is growing from this reply.';sfx.grow&&sfx.grow()}render()}
window.addCommunityComment=comment=>{if(!comment||!comment.id||!comment.parentId||!byId.has(comment.parentId))return;comments.push(comment);byId.set(comment.id,comment);open.add(comment.parentId);added.add(comment.id);hint.textContent='A new reply is growing into the root system.';sfx.grow&&sfx.grow();render()};document.querySelector('#expandAll').addEventListener('click',()=>{comments.forEach(c=>{if(children(c.id).length){open.add(c.id);children(c.id).forEach(k=>added.add(k.id))}});hint.textContent='All available roots are visible.';sfx.chime&&sfx.chime();render()});
function setZoom(value){zoom=Math.max(.75,Math.min(1.3,value));canvas.style.zoom=zoom;hint.textContent='View zoom: '+Math.round(zoom*100)+'%.'}document.querySelector('#zoomIn').onclick=()=>setZoom(zoom+.1);document.querySelector('#zoomOut').onclick=()=>setZoom(zoom-.1);document.querySelector('#fitView').onclick=()=>setZoom(1);let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(render,100)});render();