if(!document.querySelector('link[href="css/pixel-details.css"]')) document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/pixel-details.css">');
if(!document.querySelector('link[href="css/retro-modern.css"]')) document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/retro-modern.css">');
function money(n){return 'Rp'+n.toLocaleString('id-ID')}
function nav(active=''){return `<nav class="pixel-navbar container"><a class="brand" href="home.html">&#10047; FLORAVERSE</a><div class="nav-links"><a class="${active==='home'?'active':''}" href="home.html">Kebun</a><a class="${active==='forum'?'active':''}" href="forum.html">Forum</a><a class="${active==='market'?'active':''}" href="marketplace.html">Pasar</a><a class="${active==='flora'?'active':''}" href="florapedia.html">Florapedia</a><a class="${active==='donate'?'active':''}" href="donation.html">Donasi</a><a class="${active==='checkout'?'active':''}" href="checkout.html">Checkout</a></div></nav>`}
function sprite(type){return `<span class="sprite ${type}"></span>`}
document.addEventListener('DOMContentLoaded',()=>{
 const hero=document.querySelector('.hero'); if(hero) hero.insertAdjacentHTML('afterbegin','<img class="pixel-burst hero-burst" src="assets/images/pixel-starburst.png" alt="" aria-hidden="true">');
 const page=document.body.dataset.page; const navTarget=document.querySelector('[data-nav]'); if(navTarget) navTarget.innerHTML=nav(page);
 const world=document.querySelector('.page-world'); if(world) world.insertAdjacentHTML('afterbegin','<div class="pixel-vine vine-left"></div><div class="pixel-vine vine-right"></div><img class="pixel-burst burst-a" src="assets/images/pixel-starburst.png" alt="" aria-hidden="true"><img class="pixel-burst burst-b" src="assets/images/pixel-starburst.png" alt="" aria-hidden="true"><div class="pixel-butterfly page-butterfly"><i></i></div>');
 if(page==='forum') document.querySelector('#threads').innerHTML=communityThreads.map(t=>`<article class="thread-note"><h3>${t.title}</h3><span class="avatar" style="--avatar:${t.user.color}"></span>${t.user.name} <span class="tag">${t.category}</span><span style="float:right">&#128172; ${t.replies}</span></article>`).join('');
 if(page==='market') document.querySelector('#products').innerHTML=marketplaceProducts.map((p,i)=>`<article class="product" data-category="${p.category}">${sprite(p.sprite)}<h3>${p.name}</h3><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div><div class="price">${money(p.price)}</div><button class="pixel-btn add-cart" data-product="${i}">Tambah</button></article>`).join('');
 if(page==='flora') document.querySelector('#flora-list').innerHTML=florapediaEntries.map((p,i)=>`<article class="flora-entry"><div>${sprite(i%3===0?'flower':'leaf')}</div><h3>${p.name}</h3><em>${p.latin}</em><p>${p.desc}</p><span class="tag">${p.group}</span><span class="tag">${p.difficulty}</span></article>`).join('');
 if(page==='donate') document.querySelector('#organizations').innerHTML=donationOrganizations.map((o,i)=>`<article class="org"><h3>${sprite(i%2?'flower':'leaf')} ${o.name}</h3><p>${o.desc}</p><div class="progress" style="--value:${o.raised}%"><i></i></div><span>${o.raised}% dari ${o.target}</span> <a class="pixel-btn green" href="checkout.html">Donasi</a></article>`).join('');
 document.addEventListener('click',e=>{if(e.target.matches('.add-cart')){localStorage.setItem('floraCart',e.target.dataset.product);location.href='checkout.html'} if(e.target.matches('[data-success]')) document.querySelector('#success').classList.add('show')});
 const productIndex=localStorage.getItem('floraCart')||0; if(page==='checkout'){let p=marketplaceProducts[productIndex];document.querySelector('#order').innerHTML=`<div class="order-line"><span>${p.name}</span><strong>${money(p.price)}</strong></div><div class="order-line"><span>Biaya layanan hijau</span><strong>Rp2.000</strong></div><div class="order-line"><strong>Total</strong><strong>${money(p.price+2000)}</strong></div>`}
});
